name: buildandtest
on:
 workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name : Repo Template - Print Runner hostname and Ip address
     run: |
       echo "Runner Hostname : $(hostname)"
       curl http://ipinfo.io/ip