name: Deploy Web site
#on: [push, workflow_dispatch]
on:
 pull_request: #action types
  branches:
   - main
  types:
   - opened 
   - closed
 workflow_dispatch:
 schedule:
   - cron: '*/5  * * * *' # every five minutes
 push: # action filteres
   branches:
     - main
     - 'develop-*'
     - 'feature/**'
  # paths:
   #  -  src
 #  paths-ignore:
  #   - '.github/workflows/*'
jobs:
   matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [cat, dog]
        color: [pink, brown]
        include:
          - color: white
            pet: dog
    steps:
      - run: echo "Hello ${{ matrix.color }} ${{ matrix.pet }}"
   test:
     runs-on: ubuntu-latest
     steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install Node Js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Runs tests
          run: npm test 
   deploy:
     needs: test
     runs-on: ubuntu-latest
     steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install Node Js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: build project
          run:  npm run build
        - name: Deploy
          run: echo "Deploying code..this steps runs becuase the condition is true...!"
          if: github.ref == 'refs/heads/main' # Conditions to check if branch is main
   report:
    needs: [test, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
     - name: Output information
       run: |
        echo "Something went wrong"
        echo "${{ github }}"
               
